services:
  redis:
    image: redis:7.0.10
  mongo:
    image: mongo:6.0.3
  worker:
    image: proteus/worker
    build:
      context: bin/worker/
    volumes:
      - /root/.axiom/accounts/aws.json:/root/.axiom/accounts/default.json
      - /root/.axiom/modules:/root/.axiom/modules
      - /root/.ssh:/root/.ssh
      - /root/.proteus:/app
      - /root/.aws:/root/.aws
    depends_on:
    - redis
    - mongo
  api:
    image: proteus/api
    build:
      context: bin/api/
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
    - '127.0.0.1:80:80'
    depends_on:
      - redis
